#!/bin/sh
set -e

case "$1" in
    configure)
        systemctl is-active --quiet thermoservice && echo systemctl restart thermoservice || echo "Thermoservice Not running yet"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

echo -n 'Current Temperature:'
thermo

#DEBHELPER#

exit 0
