#!/bin/sh
set -e

case "$1" in
    configure)
        systemctl is-active --quiet thermoservice && systemctl restart thermoservice || echo "Thermoservice Not running yet"
        # Display current temperature if sensor is available
        if [ -x /usr/bin/thermo ]; then
            echo -n 'Current Temperature: '
            /usr/bin/thermo 2>/dev/null || echo "No DS18B20 sensor detected"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
