#!/bin/sh
set -e

case "$1" in
    configure)
        # Restart zabbix-agent2 to load the new configuration
        if systemctl is-active --quiet zabbix-agent2; then
            systemctl restart zabbix-agent2 || true
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
